// Writes contracts/registry/src/fixture.rs from the make_input.js scenario so
// the Rust test checks on-chain tree roots and a real proof against JS output.
const fs = require('fs'), path = require('path');
const { hasher } = require('./lib');
const u = require('../ref-zk-vote/circuits/conversion-utils.js');
const strip = (h) => h.replace(/^0x/, '');
(async () => {
  const H = await hasher();
  const pepper = 424242n;
  const commitments = [11111111n, 22222222n, 33333333n].map((id) => H([H([id, pepper])]));
  const vk = u.convertVKeyToSoroban(require('./build/vkey.json'));
  const pr = u.convertProofToSoroban(require('./build/proof.json'));
  const pub = require('./build/public.json');
  const dec = (s) => `"${s}"`;
  const RECIP = process.argv[2];
  const out = `// Generated by circuits/gen_fixture.js. Do not edit.
pub const COMMITMENTS: [&str; 3] = [${commitments.map((c) => dec(c.toString())).join(', ')}];
pub const ROOT: &str = ${dec(pub[0])};
pub const NULLIFIER: &str = ${dec(pub[1])};
pub const RECIPIENT: &str = "${RECIP}";
pub const RECIPIENT_FIELD: &str = ${dec(pub[3])};
pub const VK_ALPHA: &str = "${strip(vk.alpha)}";
pub const VK_BETA: &str = "${strip(vk.beta)}";
pub const VK_GAMMA: &str = "${strip(vk.gamma)}";
pub const VK_DELTA: &str = "${strip(vk.delta)}";
pub const VK_IC: [&str; ${vk.ic.length}] = [${vk.ic.map((x) => `"${strip(x)}"`).join(', ')}];
pub const PROOF_A: &str = "${strip(pr.a)}";
pub const PROOF_B: &str = "${strip(pr.b)}";
pub const PROOF_C: &str = "${strip(pr.c)}";
`;
  fs.writeFileSync(path.join(__dirname, '../contracts/registry/src/fixture.rs'), out);
  console.log('fixture written');
})();
